export const SET_FONT_LOADED = "SET_FONT_LOADED";
export const SET_SITE_READY_TO_SHOW = "SET_SITE_READY_TO_SHOW";
export const SET_COIN_FACE = "SET_COIN_FACE";
export const SET_COIN_TOSS_IN_PROGRESS = "SET_COIN_TOSS_IN_PROGRESS";
export const SET_DIALOG_INFO = "SET_DIALOG_INFO";
export const SET_IMAGES_LOADED = "SET_IMAGES_LOADED";
